# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""Generate the FHR JSON-LD context and vocabulary from the LinkML model.

The LinkML annotations in ``schemas/core.yaml`` and ``fhr_linkml.yml`` are the
single source of the term IRIs (specs/011-jsonld-mapping research R-08). This
script writes:

- ``jsonld/fhr.context.jsonld``: the JSON-LD 1.1 context, with a
  property-scoped context for every nested FHR object (data-model sections 1-2);
- ``jsonld/terms.ttl``, ``jsonld/terms.jsonld`` and ``docs/TERMS.md``: the
  FAIR-bioHeaders vocabulary as Turtle, as JSON-LD and as a documentation page
  (contracts/vocabulary.md);
- ``examples/example.fhr.jsonld`` and ``examples/minimal.fhr.jsonld``: the
  reference writer's output for the JSON examples (rule J7);
- the summary table in ``docs/MAPPINGS.md`` and the DCMI line of each term in
  ``docs/TERMS.md``, from the curated ``mappings/fhr-jsonld-dcmi.yml``.

It is also the reference JSON-LD writer (``to_jsonld``, contracts/cli.md
"Writing") and canonical reader (``canonical_record``, rule J1) that the tests,
the conformance vectors and docs/JSONLD.md follow. These need only the standard
library; generating the context needs LinkML.

``--check`` regenerates everything in memory and exits 1 with a unified diff if
a committed file differs; ``--examples`` writes only the JSON-LD examples;
``--mappings-summary`` prints the mapping summary table. The script never uses
the network.
"""

import argparse
import copy
import difflib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
LINKML = ROOT / "fhr_linkml.yml"
SCHEMA = ROOT / "fhr.json"
CONTEXT_PATH = ROOT / "jsonld" / "fhr.context.jsonld"
TERMS_PATH = ROOT / "jsonld" / "terms.ttl"
TERMS_JSONLD_PATH = ROOT / "jsonld" / "terms.jsonld"
TERMS_DOC = ROOT / "docs" / "TERMS.md"
EXAMPLES = ("example", "minimal")
MAPPING_TABLE = ROOT / "mappings" / "fhr-jsonld-dcmi.yml"
MAPPINGS_DOC = ROOT / "docs" / "MAPPINGS.md"
SUMMARY_START = "<!-- Generated by scripts/make_jsonld.py from mappings/fhr-jsonld-dcmi.yml; do not edit. -->"
SUMMARY_END = "<!-- End of generated table. -->"
RAW_MAIN_CONTEXT_URL = (
    "https://raw.githubusercontent.com/FAIR-bioHeaders/FHR-Specification/main/"
    "jsonld/fhr.context.jsonld"
)
# Contexts a canonical document may reference by URL (rule J1). Release URLs
# are added once an FHR-Specification release contains jsonld/.
KNOWN_CONTEXT_URLS = (RAW_MAIN_CONTEXT_URL,)

SDO = "http://schema.org/"
FHR = "https://w3id.org/fair-bioheaders/terms#"
XSD = "http://www.w3.org/2001/XMLSchema#"
DCT = "http://purl.org/dc/terms/"
VOCABULARY = "https://w3id.org/fair-bioheaders/terms"
PREFIXES = {"sdo": SDO, "fhr": FHR}
ROOT_CLASS = "FHR"
# Root terms that are not FHR keys. ``subjectOf`` comes from the LinkML
# annotation ``jsonld_slot_uri_if_url`` on documentation (maintainer decision 3);
# the others are supplied only by an export context (maintainer decision 2).
EXPORT_TERMS = {
    "keywords": {"@id": "sdo:keywords", "@container": "@set"},
    "url": {"@id": "sdo:url", "@type": "@id"},
    "conformsTo": {"@id": "dct:conformsTo", "@type": "@id"},
}
# Writer @type for each nested object path (data-model section 5).
RANGE_IRIS = {
    "string": "sdo:Text",
    "float": "sdo:Number",
    "integer": "sdo:Integer",
    "uri": "sdo:URL",
    "date": "sdo:Date",
}
DOMAIN_NOTES = {
    "FHR": "the FHR record",
    "VitalStats": "the `vitalStats` object",
    "AssemblySoftware": "an `assemblySoftware` item",
}


def annotations(element):
    """Return an element's LinkML annotations as a plain dict."""
    found = element.annotations
    if not found:
        return {}
    if hasattr(found, "items"):
        return {tag: value.value for tag, value in found.items()}
    from jsonasobj2 import as_dict

    return {tag: value["value"] if isinstance(value, dict) else value
            for tag, value in as_dict(found).items()}


def compact(iri):
    for prefix, namespace in (("sdo", SDO), ("fhr", FHR), ("dct", DCT), ("xsd", XSD)):
        if iri.startswith(namespace):
            return f"{prefix}:{iri[len(namespace):]}"
    return iri


def local_name(curie):
    return curie.split(":", 1)[1]


class Model:
    """The LinkML classes reachable from FHR, with keys in fhr.json order."""

    def __init__(self):
        from linkml_runtime import SchemaView

        self.view = SchemaView(str(LINKML))
        self.schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        if self.view.schema.default_prefix != "fhr":
            raise ValueError("fhr_linkml.yml must set default_prefix: fhr")

    def resolve(self, node):
        while "$ref" in node:
            target = self.schema
            for part in node["$ref"][2:].split("/"):
                target = target[part]
            node = {**target, **{k: v for k, v in node.items() if k != "$ref"}}
        return node

    def object_node(self, node):
        """The fhr.json object schema under ``node`` (through items and anyOf)."""
        node = self.resolve(node)
        if "properties" in node:
            return node
        if "items" in node:
            return self.object_node(node["items"])
        for option in node.get("anyOf", []):
            found = self.object_node(option)
            if found is not None:
                return found
        return None

    def slots(self, class_name, node):
        """Induced slots of ``class_name`` in the property order of ``node``."""
        induced = {slot.name: slot for slot in self.view.class_induced_slots(class_name)}
        order = list(node["properties"])
        if set(order) != set(induced):
            raise ValueError(f"{class_name}: LinkML slots {sorted(induced)} differ from "
                             f"fhr.json properties {sorted(order)}")
        return [induced[name] for name in order]

    def class_range(self, slot):
        """The class a slot holds (inlined), or None."""
        ranges = [slot.range] + [option.range for option in slot.any_of or []]
        classes = [name for name in ranges if name and self.view.get_class(name) is not None]
        return classes[0] if classes else None

    def multivalued(self, slot):
        return bool(slot.multivalued) or any(o.multivalued for o in slot.any_of or [])

    def iri(self, slot):
        return self.view.get_uri(slot, expand=True)

    def class_iri(self, class_name):
        return self.view.get_uri(self.view.get_class(class_name), expand=True)

    def walk(self, class_name=ROOT_CLASS, node=None, seen=None):
        """Yield ``(class_name, fhr.json node, slots)`` for every reachable class."""
        node = self.schema if node is None else node
        seen = set() if seen is None else seen
        if class_name in seen:
            return
        seen.add(class_name)
        slots = self.slots(class_name, node)
        yield class_name, node, slots
        for slot in slots:
            child = self.class_range(slot)
            if child:
                yield from self.walk(child, self.object_node(node["properties"][slot.name]),
                                     seen)


def type_terms(model, class_name):
    """The type terms the writer can emit on nodes of ``class_name``."""
    cls = model.view.get_class(class_name)
    terms = {}
    extra = annotations(cls)
    for tag in ("jsonld_type_if_orcid", "jsonld_type_if_ror"):
        if tag in extra:
            terms[local_name(extra[tag])] = extra[tag]
    class_curie = compact(model.class_iri(class_name))
    terms[local_name(class_curie)] = class_curie
    return terms


def term_definition(model, slot, node):
    if annotations(slot).get("jsonld_node_id") is True:
        return "@id"
    definition = {"@id": compact(model.iri(slot))}
    child = model.class_range(slot)
    if slot.range == "uri" or annotations(slot).get("jsonld_iri") is True:
        definition["@type"] = "@id"
    elif slot.range == "date":
        definition["@type"] = "xsd:date"
    if model.multivalued(slot):
        definition["@container"] = "@list" if slot.list_elements_ordered else "@set"
    if child:
        definition["@context"] = [None, scope(model, child, model.object_node(node))]
    return definition


def scope(model, class_name, node):
    """The property-scoped context body for nodes of ``class_name``."""
    body = {"@protected": True, **PREFIXES, **type_terms(model, class_name)}
    for slot in model.slots(class_name, node):
        body[slot.name] = term_definition(model, slot, node["properties"][slot.name])
    check_injective(class_name, body)
    return body


def expand(value, prefixes):
    value = value["@id"] if isinstance(value, dict) else value
    if value.startswith("@") or "://" in value:
        return value
    prefix, _, rest = value.partition(":")
    return prefixes[prefix] + rest


def check_injective(name, body):
    """Fail if two keys of one scope map to the same IRI (data-model rule 4)."""
    prefixes = {**PREFIXES, "xsd": XSD, "dct": DCT}
    seen = {}
    for key, value in body.items():
        if key.startswith("@") or key in prefixes:
            continue
        iri = expand(value, prefixes)
        if iri in seen:
            raise ValueError(f"scope {name}: {seen[iri]} and {key} both map to {iri}")
        seen[iri] = key


def build_context(model):
    root = {"@version": 1.1, "@protected": True, **PREFIXES, "xsd": XSD, "dct": DCT}
    root.update(type_terms(model, ROOT_CLASS))
    url_terms = {}
    for slot in model.slots(ROOT_CLASS, model.schema):
        root[slot.name] = term_definition(model, slot, model.schema["properties"][slot.name])
        alternative = annotations(slot).get("jsonld_slot_uri_if_url")
        if alternative:
            url_terms[local_name(alternative)] = {"@id": alternative, "@type": "@id"}
    root.update(url_terms)
    root.update(EXPORT_TERMS)
    check_injective(ROOT_CLASS, root)
    return {"@context": root}


# The vocabulary.


def collect_terms(model):
    """FHR-namespace classes and properties reachable from FHR (vocabulary.md)."""
    classes, properties = {}, {}
    for class_name, _, slots in model.walk():
        class_iri = model.class_iri(class_name)
        cls = model.view.get_class(class_name)
        extra = annotations(cls)
        if class_iri.startswith(FHR):
            name = class_iri[len(FHR):]
            classes[name] = {
                "comment": extra.get("vocabulary_comment") or cls.description,
                "subClassOf": [extra["vocabulary_subclass_of"]]
                if "vocabulary_subclass_of" in extra else [],
                "closeMatch": list(cls.close_mappings or []),
            }
        for slot in slots:
            iri = model.iri(slot)
            if annotations(slot).get("jsonld_node_id") is True or not iri.startswith(FHR):
                continue
            name = iri[len(FHR):]
            entry = properties.setdefault(name, {
                "comment": slot.description,
                "domain": [],
                "domain_classes": [],
                "range": [],
                "subPropertyOf": [m for m in slot.broad_mappings or [] if m.startswith("sdo:")],
            })
            domain = compact(class_iri)
            if domain not in entry["domain"]:
                entry["domain"].append(domain)
                entry["domain_classes"].append(class_name)
            ranges = [slot.range] + [option.range for option in slot.any_of or []]
            for kind in ranges:
                if not kind:
                    continue
                if model.view.get_class(kind) is not None:
                    for value in type_terms(model, kind).values():
                        if value not in entry["range"]:
                            entry["range"].append(value)
                    continue
                else:
                    base = kind
                    linkml_type = model.view.get_type(kind)
                    if kind not in RANGE_IRIS and linkml_type is not None:
                        base = {"str": "string"}.get(linkml_type.base, linkml_type.typeof)
                    value = RANGE_IRIS[base]
                if value not in entry["range"]:
                    entry["range"].append(value)
    for kind, terms in (("class", classes), ("property", properties)):
        for name, entry in terms.items():
            if not (entry["comment"] or "").strip():
                raise ValueError(f"{kind} fhr:{name} has no description (FR-002)")
    return classes, properties


def ordered(terms):
    return sorted(terms, key=lambda name: (name.casefold(), name))


def turtle_string(text):
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"@en'


RELEASE_ALIAS = "https://w3id.org/fair-bioheaders/fhr/vX.Y.Z/jsonld/"
TURTLE_HEADER = f"""# Generated by scripts/make_jsonld.py from the LinkML model; do not edit.
# Canonical URL: https://raw.githubusercontent.com/FAIR-bioHeaders/FHR-Specification/main/jsonld/terms.ttl
# Release copies: {RELEASE_ALIAS}terms.ttl
# Term IRIs never change and are never reused with another meaning.

@prefix fhr:     <{FHR}> .
@prefix sdo:     <{SDO}> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:     <http://www.w3.org/2002/07/owl#> .
@prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
@prefix dcterms: <{DCT}> .

<{VOCABULARY}> a owl:Ontology ;
    rdfs:label "FAIR-bioHeaders vocabulary"@en ;
    rdfs:comment "Terms for FAIR-bioHeaders metadata that have no schema.org equivalent. \
Generated from the FHR-Specification LinkML model; do not edit."@en ;
    dcterms:license <https://www.mozilla.org/en-US/MPL/2.0/> ;
    rdfs:seeAlso <https://github.com/FAIR-bioHeaders/FHR-Specification/blob/main/docs/TERMS.md> .
"""


def build_turtle(classes, properties):
    blocks = [TURTLE_HEADER]
    for name in ordered(classes):
        entry = classes[name]
        lines = [f"fhr:{name} a rdfs:Class ;",
                 f"    rdfs:label {turtle_string(name)} ;",
                 f"    rdfs:comment {turtle_string(entry['comment'])} ;"]
        if entry["subClassOf"]:
            lines.append(f"    rdfs:subClassOf {', '.join(entry['subClassOf'])} ;")
        if entry["closeMatch"]:
            lines.append(f"    skos:closeMatch {', '.join(entry['closeMatch'])} ;")
        lines.append(f"    rdfs:isDefinedBy <{VOCABULARY}> .")
        blocks.append("\n".join(lines) + "\n")
    for name in ordered(properties):
        entry = properties[name]
        lines = [f"fhr:{name} a rdf:Property ;",
                 f"    rdfs:label {turtle_string(name)} ;",
                 f"    rdfs:comment {turtle_string(entry['comment'])} ;",
                 f"    sdo:domainIncludes {', '.join(entry['domain'])} ;",
                 f"    sdo:rangeIncludes {', '.join(entry['range'])} ;"]
        if entry["subPropertyOf"]:
            lines.append(f"    rdfs:subPropertyOf {', '.join(entry['subPropertyOf'])} ;")
        lines.append(f"    rdfs:isDefinedBy <{VOCABULARY}> .")
        blocks.append("\n".join(lines) + "\n")
    return "\n".join(blocks)


JSONLD_PREFIXES = {
    "fhr": FHR,
    "sdo": SDO,
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "owl": "http://www.w3.org/2002/07/owl#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "dcterms": DCT,
}


def _iris(curies):
    return [{"@id": curie} for curie in curies]


def _text(value):
    return {"@value": value, "@language": "en"}


def build_terms_jsonld(classes, properties):
    """The vocabulary as JSON-LD, with the same triples as ``build_turtle``."""
    defined_by = {"@id": VOCABULARY}
    graph = [{
        "@id": VOCABULARY,
        "@type": "owl:Ontology",
        "rdfs:label": _text("FAIR-bioHeaders vocabulary"),
        "rdfs:comment": _text("Terms for FAIR-bioHeaders metadata that have no schema.org "
                              "equivalent. Generated from the FHR-Specification LinkML "
                              "model; do not edit."),
        "dcterms:license": {"@id": "https://www.mozilla.org/en-US/MPL/2.0/"},
        "rdfs:seeAlso": {"@id": "https://github.com/FAIR-bioHeaders/FHR-Specification/blob/"
                                "main/docs/TERMS.md"},
    }]
    for name in ordered(classes):
        entry = classes[name]
        node = {"@id": f"fhr:{name}", "@type": "rdfs:Class",
                "rdfs:label": _text(name), "rdfs:comment": _text(entry["comment"])}
        if entry["subClassOf"]:
            node["rdfs:subClassOf"] = _iris(entry["subClassOf"])
        if entry["closeMatch"]:
            node["skos:closeMatch"] = _iris(entry["closeMatch"])
        node["rdfs:isDefinedBy"] = defined_by
        graph.append(node)
    for name in ordered(properties):
        entry = properties[name]
        node = {"@id": f"fhr:{name}", "@type": "rdf:Property",
                "rdfs:label": _text(name), "rdfs:comment": _text(entry["comment"]),
                "sdo:domainIncludes": _iris(entry["domain"]),
                "sdo:rangeIncludes": _iris(entry["range"])}
        if entry["subPropertyOf"]:
            node["rdfs:subPropertyOf"] = _iris(entry["subPropertyOf"])
        node["rdfs:isDefinedBy"] = defined_by
        graph.append(node)
    return json.dumps({"@context": JSONLD_PREFIXES, "@graph": graph}, indent=2) + "\n"


TERMS_INTRO = f"""# FAIR-bioHeaders vocabulary

<!-- Generated by scripts/make_jsonld.py from the LinkML model (schemas/core.yaml and
fhr_linkml.yml); do not edit. -->

This page defines the FAIR-bioHeaders terms that the [JSON-LD context](../jsonld/fhr.context.jsonld)
uses where schema.org has no suitable term. The namespace is `{FHR}`. It is unversioned: a term
IRI never changes and is never reused with another meaning. A deprecated term is kept and marked
deprecated.

- Machine-readable forms: [jsonld/terms.ttl](../jsonld/terms.ttl) (Turtle) and
  [jsonld/terms.jsonld](../jsonld/terms.jsonld) (JSON-LD).
- How records use the terms: [JSONLD.md](JSONLD.md) and the
  [mapping table](../mappings/fhr-jsonld-dcmi.yml).
- Licence: MPL-2.0. To cite a term, give its IRI and the FHR-Specification release.

Each heading is the term's local name, so `{FHR}checksum` is the section `#checksum` below.
"""


def curie_label(curie):
    return local_name(curie)


def build_terms_md(classes, properties, dcmi=None):
    parts = [TERMS_INTRO, "## Classes\n"]
    for name in ordered(classes):
        entry = classes[name]
        lines = [f"### {name}\n", f"`{FHR}{name}`. Class.\n", entry["comment"] + "\n"]
        bullets = []
        if entry["subClassOf"]:
            bullets.append("- Subclass of: " + ", ".join(f"`{c}`" for c in entry["subClassOf"]))
        if entry["closeMatch"]:
            bullets.append("- Close match: " + ", ".join(f"`{c}`" for c in entry["closeMatch"]))
        if bullets:
            lines.append("\n".join(bullets) + "\n")
        parts.append("\n".join(lines))
    parts.append("## Properties\n")
    for name in ordered(properties):
        entry = properties[name]
        used_on = ", ".join(
            f"{curie_label(domain)} ({DOMAIN_NOTES.get(cls, cls)})"
            for domain, cls in zip(entry["domain"], entry["domain_classes"])
        )
        bullets = [f"- Used on: {used_on}",
                   "- Value: " + ", ".join(curie_label(r) for r in entry["range"])]
        if entry["subPropertyOf"]:
            bullets.append("- Subproperty of: "
                           + ", ".join(f"`{p}`" for p in entry["subPropertyOf"]))
        if dcmi is not None:
            bullets.append(f"- DCMI: {dcmi[name]}")
        parts.append("\n".join([f"### {name}\n", f"`{FHR}{name}`. Property.\n",
                                entry["comment"] + "\n", "\n".join(bullets) + "\n"]))
    return "\n".join(parts)


# The reference writer and canonical reader (contracts/cli.md, docs/JSONLD.md).

# The Bioschemas Dataset profile release whose minimum properties are checked.
# Dataset 1.1 was still a DRAFT on 2026-10-10 (https://bioschemas.org/profiles/).
BIOSCHEMAS_DATASET_PROFILE = "https://bioschemas.org/profiles/Dataset/1.0-RELEASE"
# Minimum properties of that profile beside @context, @type and dct:conformsTo:
# (Bioschemas name, the key that carries it in the written document).
BIOSCHEMAS_MINIMUM = (
    ("@id", "@id"),
    ("description", "documentation"),
    ("identifier", "identifier"),
    ("keywords", "keywords"),
    ("license", "reuseConditions"),
    ("name", "genome"),
    ("url", "url"),
)
NODE_TYPES = {"taxon": "Taxon", "accessionID": "PropertyValue", "vitalStats": "VitalStats"}
AUTHOR_KEYS = ("metadataAuthor", "assemblyAuthor")
# fhr.json's orcidUri pattern (a prefix match), and the ROR identifier form.
ORCID_URI = re.compile(r"https://orcid\.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]")
ROR_URI = re.compile(r"https://ror\.org/0[0-9a-z]{6}[0-9]{2}")
# An absolute URL: a scheme, "://", and no whitespace (maintainer decision 3).
ABSOLUTE_URL = re.compile(r"[A-Za-z][A-Za-z0-9+.-]*://\S+")
EXPORT_KEYS = ("id", "url", "keywords")
# Root keys of a written document that carry export metadata, not FHR fields.
EXPORT_OUTPUT = ("@id", "keywords", "url", "conformsTo")
URL_TERM = "subjectOf"
NOT_CANONICAL = (
    "this JSON-LD is not in the canonical FAIR-bioHeaders form (rule J1 of "
    "FHR-Specification docs/JSONLD.md); reading other JSON-LD forms is not supported yet"
)


def load_context():
    return json.loads(CONTEXT_PATH.read_text(encoding="utf-8"))


def author_type(item):
    """data-model section 5: ORCID gives Person, ROR Organization, else Agent."""
    uri = item.get("uri")
    if isinstance(uri, str) and ORCID_URI.match(uri):
        return "Person"
    if isinstance(uri, str) and ROR_URI.fullmatch(uri):
        return "Organization"
    return "Agent"


def is_absolute_url(value):
    return isinstance(value, str) and ABSOLUTE_URL.fullmatch(value) is not None


def check_export(export):
    """Validate an export context: optional id, url and keywords (provisional)."""
    if not isinstance(export, dict):
        raise ValueError("export context must be a mapping with id, url and/or keywords")
    unknown = sorted(set(export) - set(EXPORT_KEYS))
    if unknown:
        raise ValueError(f"export context: unknown key {', '.join(map(str, unknown))}; "
                         "allowed: id, url, keywords")
    for key in ("id", "url"):
        if key in export and not is_absolute_url(export[key]):
            raise ValueError(f"export context: {key} must be an absolute URL")
    keywords = export.get("keywords", ["x"])
    if not (isinstance(keywords, list) and keywords
            and all(isinstance(word, str) and word.strip() for word in keywords)):
        raise ValueError("export context: keywords must be a non-empty list of non-empty strings")
    return export


def _present(value):
    if isinstance(value, str):
        return bool(value.strip())
    if isinstance(value, list):
        return bool(value)
    return value is not None


def bioschemas_missing(document):
    """The Bioschemas Dataset minimum properties a written document lacks."""
    return [name for name, key in BIOSCHEMAS_MINIMUM if not _present(document.get(key))]


def _reserved_keys(value, path):
    if isinstance(value, dict):
        for key, item in value.items():
            here = f"{path}.{key}" if path else key
            if key.startswith("@"):
                raise ValueError(f"JSON-LD: {here} starts with @, which JSON-LD reserves; "
                                 "it cannot be written")
            _reserved_keys(item, here)
    elif isinstance(value, list):
        for index, item in enumerate(value):
            _reserved_keys(item, f"{path}[{index}]")


def _typed(key, value):
    if key in NODE_TYPES and isinstance(value, dict):
        return {"@type": NODE_TYPES[key], **copy.deepcopy(value)}
    if key in AUTHOR_KEYS and isinstance(value, list):
        return [{"@type": author_type(item), **copy.deepcopy(item)}
                if isinstance(item, dict) else copy.deepcopy(item) for item in value]
    if key == "assemblySoftware" and isinstance(value, list):
        return [{"@type": "SoftwareApplication", **copy.deepcopy(item)}
                if isinstance(item, dict) else copy.deepcopy(item) for item in value]
    return copy.deepcopy(value)


def to_jsonld(record, export=None, context=None):
    """The JSON-LD document for an FHR record (contracts/cli.md "Writing")."""
    _reserved_keys(record, "")
    for key in (URL_TERM, *EXPORT_OUTPUT):
        if key in record:
            raise ValueError(f"JSON-LD: the root key {key} is reserved for JSON-LD output")
    if export is not None:
        export = check_export(export)
    context = load_context() if context is None else context
    document = {"@context": context["@context"], "@type": "Dataset"}
    if export and "id" in export:
        document["@id"] = export["id"]
    for key, value in record.items():
        if key == "documentation" and is_absolute_url(value):
            document[URL_TERM] = value
        else:
            document[key] = _typed(key, value)
    if export:
        for key in ("keywords", "url"):
            if key in export:
                document[key] = copy.deepcopy(export[key])
        if not bioschemas_missing(document):
            document["conformsTo"] = BIOSCHEMAS_DATASET_PROFILE
    return document


def jsonld_text(record, export=None, context=None):
    return json.dumps(to_jsonld(record, export, context), ensure_ascii=False, indent=2) + "\n"


def scope_terms(context=None):
    """Property terms of the nested scopes whose objects FHR leaves open."""
    root = (load_context() if context is None else context)["@context"]
    terms = {}
    for key in ("taxon", *AUTHOR_KEYS, "accessionID", "vitalStats"):
        body = root[key]["@context"][1]
        terms[key] = {term for term, value in body.items()
                      if isinstance(value, dict) or value == "@id"}
    return terms


def unmapped_keys(record, context=None):
    """Paths of nested keys that have no term in their scope (research R-07)."""
    terms = scope_terms(context)
    found = []
    for key, value in record.items():
        if key not in terms:
            continue
        if isinstance(value, dict):
            items = [(key, value)]
        elif isinstance(value, list):
            items = [(f"{key}[{index}]", item) for index, item in enumerate(value)
                     if isinstance(item, dict)]
        else:
            items = []
        for path, item in items:
            found += [f"{path}.{name}" for name in item if name not in terms[key]]
    return found


def is_canonical(document, context=None):
    """Rule J1: a bundled context, and no keyword but @type (and a root @id)."""
    if not isinstance(document, dict) or "@context" not in document:
        return False
    bundled = (load_context() if context is None else context)["@context"]
    value = document["@context"]
    if not (value == bundled or (isinstance(value, str) and value in KNOWN_CONTEXT_URLS)):
        return False
    if "@id" in document and not isinstance(document["@id"], str):
        return False

    def plain(node, root):
        if isinstance(node, list):
            return all(plain(item, False) for item in node)
        if not isinstance(node, dict):
            return True
        for key, item in node.items():
            if key == "@type":
                if not (isinstance(item, str)
                        or isinstance(item, list) and all(isinstance(t, str) for t in item)):
                    return False
            elif key.startswith("@"):
                if not (root and key in ("@context", "@id")):
                    return False
            elif not plain(item, False):
                return False
        return True

    return plain(document, True)


def _without_types(value):
    if isinstance(value, dict):
        return {key: _without_types(item) for key, item in value.items() if key != "@type"}
    if isinstance(value, list):
        return [_without_types(item) for item in value]
    return value


def canonical_record(document, warn=None, context=None):
    """Rule J1: set @context and @type aside; restore documentation; drop export terms."""
    if not is_canonical(document, context):
        raise ValueError(NOT_CANONICAL)
    record = {}
    for key, value in document.items():
        if key in ("@context", "@type"):
            continue
        if key in EXPORT_OUTPUT:
            if warn is not None:
                warn(f"JSON-LD: {key} is export metadata, not an FHR field; it was not kept")
            continue
        if key == URL_TERM:
            if "documentation" in document:
                raise ValueError("JSON-LD gives both documentation and subjectOf")
            if not isinstance(value, str):
                raise ValueError("JSON-LD subjectOf must be a string")
            key = "documentation"
        record[key] = _without_types(value)
    return record


# The pinned schema.org subset (research R-14, R-17).

SCHEMAORG_SUBSET = ROOT / "tests" / "fixtures" / "schemaorg-v30.1-subset.json"
# SHA-256 of schemaorg-current-https.jsonld as retrieved from
# https://schema.org/version/latest/schemaorg-current-https.jsonld on 2026-10-10,
# when v30.1 was the current release.
SCHEMAORG_SHA256 = "0a4b8c4c910fc831ec8695196510973390906a5ee34dc6b862dfec4d21a12f74"
SCHEMAORG_SOURCE = (
    "Derived from schema.org v30.1 (https://schema.org/docs/releases.html#v30.1), "
    "CC BY-SA 3.0, https://schema.org/docs/terms.html"
)
# Superclasses and datatypes, and relatedLink for the negative domain test
# (research R-03: its domain is WebPage, so it is rejected on Dataset).
SCHEMAORG_BASE_TERMS = ("Thing", "CreativeWork", "StructuredValue", "Intangible", "Text",
                        "URL", "Number", "Integer", "Date", "DateTime", "relatedLink")


def schemaorg_subset(source, context=None):
    """The schema.org terms the context uses, from a local copy of the release file."""
    import hashlib

    data = Path(source).read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SCHEMAORG_SHA256:
        raise ValueError(f"{source}: SHA-256 {digest} is not the pinned schema.org file")
    graph = {node["@id"]: node for node in json.loads(data)["@graph"]}
    context = load_context() if context is None else context
    names = set(re.findall(r'"sdo:([A-Za-z]+)"', json.dumps(context))) | set(SCHEMAORG_BASE_TERMS)

    def ids(value):
        value = value if isinstance(value, list) else [] if value is None else [value]
        return sorted(item["@id"].split(":", 1)[1] for item in value
                      if item["@id"].startswith("schema:"))

    terms = {}
    for name in sorted(names):
        node = graph.get(f"schema:{name}")
        if node is None:
            raise ValueError(f"schema.org has no term {name}")
        kinds = node["@type"] if isinstance(node["@type"], list) else [node["@type"]]
        parts = node.get("schema:isPartOf")
        parts = parts if isinstance(parts, list) else [parts] if parts else []
        terms[name] = {
            "type": "Property" if "rdf:Property" in kinds else "Class",
            "domainIncludes": ids(node.get("schema:domainIncludes")),
            "rangeIncludes": ids(node.get("schema:rangeIncludes")),
            "subClassOf": ids(node.get("rdfs:subClassOf")),
            "pending": any(part["@id"] == "https://pending.schema.org" for part in parts),
        }
    return {"_source": SCHEMAORG_SOURCE, "_sha256": SCHEMAORG_SHA256,
            "_retrieved": "https://schema.org/version/latest/schemaorg-current-https.jsonld "
                          "(2026-10-10, release v30.1)",
            "terms": terms}


def example_outputs(context):
    outputs = {}
    for stem in EXAMPLES:
        record = json.loads((ROOT / "examples" / f"{stem}.fhr.json").read_text(encoding="utf-8"))
        outputs[ROOT / "examples" / f"{stem}.fhr.jsonld"] = jsonld_text(record, context=context)
    return outputs


# The mapping table summaries (US2).


def load_table():
    import yaml

    return yaml.safe_load(MAPPING_TABLE.read_text(encoding="utf-8"))


def short(iri):
    if iri in ("@id", "none"):
        return iri
    for prefix, namespace in (("schema", SDO), ("fhr", FHR), ("dcterms", DCT)):
        if iri.startswith(namespace):
            return f"{prefix}:{iri[len(namespace):]}"
    return iri


def mappings_summary(table):
    """The Markdown summary of the mapping table: one row per FHR path."""
    lines = ["| FHR path | JSON-LD term | JSON-LD kind | DCMI term | DCMI kind |",
             "| --- | --- | --- | --- | --- |"]
    for entry in table["entries"]:
        dcmi = entry["dcmi"]
        lines.append("| `{}` | `{}` | {} | {} | {} |".format(
            entry["path"], short(entry["jsonld"]["term"]), entry["jsonld"]["kind"],
            "; ".join(f"`{short(m['term'])}`" if m["term"] != "none" else "none" for m in dcmi),
            "; ".join(m["kind"] for m in dcmi)))
    return "\n".join(lines) + "\n"


def dcmi_lines(table):
    """The DCMI line of each fhr: property in docs/TERMS.md."""
    lines = {}
    for entry in table["entries"]:
        term = entry["jsonld"]["term"]
        if not term.startswith(FHR):
            continue
        texts = [f"`{short(m['term'])}` ({m['kind']})" for m in entry["dcmi"] if m["term"] != "none"]
        lines[term[len(FHR):]] = ("; ".join(texts) if texts else "none") + \
            " (see the [mapping table](../mappings/fhr-jsonld-dcmi.yml))"
    return lines


def mappings_doc(table):
    text = MAPPINGS_DOC.read_text(encoding="utf-8")
    start, end = text.find(SUMMARY_START), text.find(SUMMARY_END)
    if start < 0 or end < start:
        raise ValueError("docs/MAPPINGS.md has no generated summary markers")
    return text[:start] + SUMMARY_START + "\n\n" + mappings_summary(table) + "\n" + text[end:]


def generate():
    """Return ``{path: text}`` for every generated file."""
    model = Model()
    context = build_context(model)
    classes, properties = collect_terms(model)
    table = load_table()
    return {
        CONTEXT_PATH: json.dumps(context, indent=2) + "\n",
        TERMS_PATH: build_turtle(classes, properties),
        TERMS_JSONLD_PATH: build_terms_jsonld(classes, properties),
        TERMS_DOC: build_terms_md(classes, properties, dcmi_lines(table)),
        MAPPINGS_DOC: mappings_doc(table),
        **example_outputs(context),
    }


def check(outputs):
    stale = False
    for path, text in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != text:
            stale = True
            relative = path.relative_to(ROOT).as_posix()
            sys.stdout.writelines(difflib.unified_diff(
                current.splitlines(keepends=True), text.splitlines(keepends=True),
                f"a/{relative}", f"b/{relative} (generated)"))
    if stale:
        print("Generated JSON-LD files are out of date; run python scripts/make_jsonld.py",
              file=sys.stderr)
        return 1
    print("JSON-LD context, vocabulary and generated documents are up to date.")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 with a diff if a generated file is out of date")
    parser.add_argument("--examples", action="store_true",
                        help="write only examples/*.fhr.jsonld from the committed context")
    parser.add_argument("--mappings-summary", action="store_true",
                        help="print the mapping table summary (Markdown) and exit")
    parser.add_argument("--schemaorg-subset", metavar="SOURCE",
                        help="write tests/fixtures/schemaorg-v30.1-subset.json from a local "
                             "copy of schemaorg-current-https.jsonld (manual download)")
    args = parser.parse_args(argv)
    if args.mappings_summary:
        sys.stdout.write(mappings_summary(load_table()))
        return 0
    try:
        if args.schemaorg_subset:
            subset = schemaorg_subset(args.schemaorg_subset)
            outputs = {SCHEMAORG_SUBSET: json.dumps(subset, indent=2) + "\n"}
        elif args.examples:
            outputs = example_outputs(load_context())
        else:
            outputs = generate()
    except ValueError as error:
        print(f"make_jsonld: {error}", file=sys.stderr)
        return 1
    if args.check:
        return check(outputs)
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
